version: 0.3.1
slug: silabs_multiprotocol
name: Silicon Labs Multiprotocol
description: Zigbee and OpenThread multiprotocol add-on
url: https://github.com/home-assistant/addons-development/tree/master/silabs-multiprotocol
arch:
  - armv7
# Currently zigbeed crashes with *** stack smashing detected ***
#  - aarch64
hassio_api: true
# IPC is only used within the Add-on
host_ipc: false
host_network: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
image: homeassistant/{arch}-addon-silabs-multiprotocol
init: false
options:
  device: null
  cpcd_trace: false
  socat_trace: false
  otbr_enable: true
  otbr_debug: false
ports:
  9999/tcp: null
ports_description:
  9999/tcp: EmberZNet EZSP/ASH port
schema:
  device: device(subsystem=tty)
  cpcd_trace: bool
  socat_trace: bool
  otbr_enable: bool
  otbr_debug: bool
stage: experimental
startup: services
ingress: true
ingress_port: 8080
panel_title: OpenThread
panel_icon: mdi:view-grid-plus-outline
panel_admin: true
