---
build_from:
  aarch64: ghcr.io/home-assistant-libs/python-matter-server:4.0.0b0
  amd64: ghcr.io/home-assistant-libs/python-matter-server:4.0.0b0
args:
  BASHIO_VERSION: 0.15.0
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.5.0
