#!/bin/bash
# ==============================================================================
# Start Co-Processor Communication Daemon (CPCd)
# ==============================================================================
echo "Starting cpcd..."
exec s6-notifyoncheck -s 300 -w 300 "/usr/bin/stdbuf" -o0 /usr/local/bin/cpcd
